name: Deploy Angular to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MONKLANG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MONKLANG_AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular Application
        run: npm run build --prod

      - name: Deploy to S3
        run: |
          aws s3 cp dist/monklang/ s3://${{ secrets.MONKLANG_AWS_S3_BUCKET }} --recursive
